{
    "name": "Viavista Monitoring Logs",
    "version": "19.0.1.0.0",
    "category": "Technical",
    "summary": "Enhanced error tracking with log grouping and retention management",
    "author": "Viavista d.o.o.",
    "website": "https://github.com/viavista/viavista-odoo-modules",
    "license": "LGPL-3",
    "depends": ["base"],
    "data": [
        "security/monitoring_groups.xml",
        "security/ir.model.access.csv",
        "data/ir_cron.xml",
        "views/ir_logging_views.xml",
        "views/res_config_settings_views.xml",
        "views/menus.xml",
    ],
    "installable": True,
    "application": True,
}
